Abibubble/noffle-my-needs

README.md
Add basic readme template to build on
=> docs: Add readme template to start project

README.md
=> Change Main Heading

README.md
Add more to template, updating details to relate to this project, and Heroku deployment steps
=> docs: Fix linting issues and add extra details to work on

README.md
Adding pronouns area on user database model
=> docs: Add pronouns

app.py, templates/index.html
Set variables and include code to connect to Heroku and to our database
=> maint: Connect to Heroku and DB

templates/base.html
All meta tags are updated, including social media information for correct display when linked on social media
=> feat: Add all meta tags and social media references

static/js/script.js, templates/base.html
Add basic footer with auto-updating copyright year
=> feat: Add auto-updating copyright functionality

app.py, templates/manage_users.html
Added admin toggle & delete user buttons & routes
=> Added admin toggle & delete user buttons & routes

static/css/styles.css, static/js/script.js, templates/login.html
feat: Add styling to login form
=> feat: Add styling to login form

app.py, templates/set_noffles.html
Add if statement to check if user_noffles exists because it was causing an error when a new user registers as user_noffles hasn't been created yet.
=> Add if statement to check if user_noffles exists

static/css/styles.css, templates/login.html, templates/register.html
style: Style register and login pages
* horizontally and vertically center icons
* add equal gaps between input fields
* add link to the register page to direct users to login page
=> style: Style register and login pages

app.py
Admins can now access the manage users page
=> Fixed incorrect managed users redirect

templates/manage_noffles.html, templates/manage_users.html, templates/office.html, templates/profile.html, templates/set_noffles.html
style: Edit styling on page titles of all pages
=> style: Edit styling on page titles of all pages

static/css/styles.css, templates/profile.html
style: Polish up style on profile page
=> style: Polish up style on profile page

templates/profile.html
style: Add responsiveness to profile page
=> style: Add responsiveness to profile page

app.py
=> bug: Fix debug mode

templates/base.html
bug: Fix navbar responsiveness with navbar toggler
=> bug: Fix navbar responsiveness with navbar toggler

templates/set_noffles.html
style: Update icon for unselected noffle
=> style: Update icon for unselected noffle

static/css/styles.css, templates/manage_users.html
style: Update style in manage_users.html
=> style: Update style in manage_users.html

app.py
Rephrase flash messages appearing when removing and adding Noffles to one's profile
=> Rephrase flash messages appearing when removing and adding Noffles to one's profile

static/css/styles.css
Add padding to body so footer does not cover anything, responsive
=> Add padding to body so footer does not cover anything, responsive

static/css/styles.css, templates/base.html
style: Fix flash messages styling
=> style: Fix flash messages styling

static/css/styles.css, templates/office.html
style: Style the Office page as well as the user cards
=> style: Style the Office page as well as the user cards

templates/set_noffles.html
style: Style Set My Noffles page
=> style: Style Set My Noffles page

templates/manage_noffles.html, templates/manage_users.html
style: Style Manage Users and Manage Users pages for uniform style
=> style: Style Manage Users and Manage Users pages for uniform style
